// Code generated by mockery v2.51.0. DO NOT EDIT.

package rabbit

import (
	mock "github.com/stretchr/testify/mock"
	rabbit "github.com/xBlaz3kx/DevX/rabbit"
)

// MockConsumerOpt is an autogenerated mock type for the ConsumerOpt type
type MockConsumerOpt struct {
	mock.Mock
}

type MockConsumerOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerOpt) EXPECT() *MockConsumerOpt_Expecter {
	return &MockConsumerOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockConsumerOpt) Execute(_a0 *rabbit.ConsumerOpts) {
	_m.Called(_a0)
}

// MockConsumerOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConsumerOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *rabbit.ConsumerOpts
func (_e *MockConsumerOpt_Expecter) Execute(_a0 interface{}) *MockConsumerOpt_Execute_Call {
	return &MockConsumerOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockConsumerOpt_Execute_Call) Run(run func(_a0 *rabbit.ConsumerOpts)) *MockConsumerOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*rabbit.ConsumerOpts))
	})
	return _c
}

func (_c *MockConsumerOpt_Execute_Call) Return() *MockConsumerOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumerOpt_Execute_Call) RunAndReturn(run func(*rabbit.ConsumerOpts)) *MockConsumerOpt_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockConsumerOpt creates a new instance of MockConsumerOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerOpt {
	mock := &MockConsumerOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
