// Code generated by mockery v2.51.0. DO NOT EDIT.

package rabbit

import (
	mock "github.com/stretchr/testify/mock"
	rabbit "github.com/xBlaz3kx/DevX/rabbit"
)

// MockPublishOpt is an autogenerated mock type for the PublishOpt type
type MockPublishOpt struct {
	mock.Mock
}

type MockPublishOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublishOpt) EXPECT() *MockPublishOpt_Expecter {
	return &MockPublishOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockPublishOpt) Execute(_a0 *rabbit.PublisherOptions) {
	_m.Called(_a0)
}

// MockPublishOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPublishOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *rabbit.PublisherOptions
func (_e *MockPublishOpt_Expecter) Execute(_a0 interface{}) *MockPublishOpt_Execute_Call {
	return &MockPublishOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockPublishOpt_Execute_Call) Run(run func(_a0 *rabbit.PublisherOptions)) *MockPublishOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*rabbit.PublisherOptions))
	})
	return _c
}

func (_c *MockPublishOpt_Execute_Call) Return() *MockPublishOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublishOpt_Execute_Call) RunAndReturn(run func(*rabbit.PublisherOptions)) *MockPublishOpt_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockPublishOpt creates a new instance of MockPublishOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublishOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublishOpt {
	mock := &MockPublishOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
