// Code generated by mockery v2.51.0. DO NOT EDIT.

package observability

import (
	mock "github.com/stretchr/testify/mock"
	observability "github.com/xBlaz3kx/DevX/observability"
)

// MockMetricMiddlewareOpt is an autogenerated mock type for the MetricMiddlewareOpt type
type MockMetricMiddlewareOpt struct {
	mock.Mock
}

type MockMetricMiddlewareOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricMiddlewareOpt) EXPECT() *MockMetricMiddlewareOpt_Expecter {
	return &MockMetricMiddlewareOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockMetricMiddlewareOpt) Execute(_a0 *observability.MetricMiddlewareOpts) {
	_m.Called(_a0)
}

// MockMetricMiddlewareOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockMetricMiddlewareOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *observability.MetricMiddlewareOpts
func (_e *MockMetricMiddlewareOpt_Expecter) Execute(_a0 interface{}) *MockMetricMiddlewareOpt_Execute_Call {
	return &MockMetricMiddlewareOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockMetricMiddlewareOpt_Execute_Call) Run(run func(_a0 *observability.MetricMiddlewareOpts)) *MockMetricMiddlewareOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*observability.MetricMiddlewareOpts))
	})
	return _c
}

func (_c *MockMetricMiddlewareOpt_Execute_Call) Return() *MockMetricMiddlewareOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricMiddlewareOpt_Execute_Call) RunAndReturn(run func(*observability.MetricMiddlewareOpts)) *MockMetricMiddlewareOpt_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockMetricMiddlewareOpt creates a new instance of MockMetricMiddlewareOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricMiddlewareOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricMiddlewareOpt {
	mock := &MockMetricMiddlewareOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
