// Code generated by mockery v2.51.0. DO NOT EDIT.

package util

import (
	mock "github.com/stretchr/testify/mock"
	util "github.com/xBlaz3kx/DevX/util"
)

// MockPaginationOpt is an autogenerated mock type for the PaginationOpt type
type MockPaginationOpt struct {
	mock.Mock
}

type MockPaginationOpt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaginationOpt) EXPECT() *MockPaginationOpt_Expecter {
	return &MockPaginationOpt_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockPaginationOpt) Execute(_a0 *util.PaginationOpts) {
	_m.Called(_a0)
}

// MockPaginationOpt_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockPaginationOpt_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *util.PaginationOpts
func (_e *MockPaginationOpt_Expecter) Execute(_a0 interface{}) *MockPaginationOpt_Execute_Call {
	return &MockPaginationOpt_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockPaginationOpt_Execute_Call) Run(run func(_a0 *util.PaginationOpts)) *MockPaginationOpt_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*util.PaginationOpts))
	})
	return _c
}

func (_c *MockPaginationOpt_Execute_Call) Return() *MockPaginationOpt_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPaginationOpt_Execute_Call) RunAndReturn(run func(*util.PaginationOpts)) *MockPaginationOpt_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockPaginationOpt creates a new instance of MockPaginationOpt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaginationOpt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaginationOpt {
	mock := &MockPaginationOpt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
